/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./node_modules/react-tailwindcss-datepicker/dist/index.esm.js",
  ],
  darkMode: "class",
  theme: {
    screens: {
      mobile: "410px",
      tablet: "783px",
      laptop: "1024px",
      desktop: "1280px",
    },
    colors: {
      background: "#E8E6E3",
      gray: "#303436",
      black: "#000000",
      white: "#FFFFFF",
      messageReceived: "#ccd0ff",
      messageSent: "#d3d3d3",
      lightGray: "#DDDEEB",
      // Adicione as cores dos temas
      theme: {
        light: {
          primaryBackgroundFrom: "#dddeeb",
          primaryBackgroundTo: "#ccd0ff",
          cardBackground: "#FFFFFF",
          cardHover: "#969ef592",
          messageReceived: "#ccd0ff",
          messageSent: "#d3d3d3",
          hashtag: "#969EF5",
          highlightHover: "#c8cdfc",
        },
        dark: {
          primaryBackgroundFrom: "#1a1a2e",
          primaryBackgroundTo: "#16213e",
          cardBackground: "#2a2a40",
          cardHover: "#0f3460",
          messageReceived: "#1f4068",
          messageSent: "#3a3a3a",
          hashtag: "#e94560",
          highlightHover: "#e94560",
        },
        magentaDark: {
          primaryBackgroundFrom: "#1e1e2f",
          primaryBackgroundTo: "#2a0a2a",
          cardBackground: "#3a1a3a",
          cardHover: "#ff00ff",
          messageReceived: "#ff00ff",
          messageSent: "#4a4a4a",
          hashtag: "#ff00ff",
          highlightHover: "#ff00ff",
        },
        greenLight: {
          primaryBackgroundFrom: "#e0f7fa",
          primaryBackgroundTo: "#b2ebf2",
          cardBackground: "#FFFFFF",
          cardHover: "#80cbc4",
          messageReceived: "#b2ebf2",
          messageSent: "#e0e0e0",
          hashtag: "#009688",
          highlightHover: "#80cbc4",
        },
        pinkLight: {
          primaryBackgroundFrom: "#fce4ec",
          primaryBackgroundTo: "#f8bbd0",
          cardBackground: "#FFFFFF",
          cardHover: "#f48fb1",
          messageReceived: "#f8bbd0",
          messageSent: "#e0e0e0",
          hashtag: "#e91e63",
          highlightHover: "#f48fb1",
        },
        darkMagenta: {
          primaryBackgroundFrom: "#1a1a1a",
          primaryBackgroundTo: "#2a0a2a",
          cardBackground: "#2a2a2a",
          cardHover: "#ff00ff",
          messageReceived: "#ff00ff",
          messageSent: "#4a4a4a",
          hashtag: "#ff00ff",
          highlightHover: "#ff00ff",
        },
        darkYellow: {
          primaryBackgroundFrom: "#1a1a1a",
          primaryBackgroundTo: "#2a2a00",
          cardBackground: "#2a2a2a",
          cardHover: "#ffcc00",
          messageReceived: "#ffcc00",
          messageSent: "#4a4a4a",
          hashtag: "#ffcc00",
          highlightHover: "#ffcc00",
        },
      },
    },
    extend: {
      fontFamily: {
        heading: ["Poppins", "sans-serif"], // Fonte para títulos
        body: ["Roboto", "sans-serif"], // Fonte para textos
      },
    },
  },
  plugins: [],
};
